### ISSUE TITLE
Publish plugin to hexo to add visibility

### ISSUE THREAD

**Issue by matthewsanders** [tea3/hexo-generator-amp#10]
The process is documented here:

https://hexo.io/docs/plugins.html

**Comment by matthewsanders** [comment]
Added info to a pull request on hexo site. https://github.com/hexojs/site/pull/214

**Comment by tea3** [comment]
@matthewsanders Thank you for PullRequest. I learned a lot from your advice : )

**Comment by matthewsanders** [comment]
No Problem.

You can also find more info on managing github projects [here](https://help.github.com/categories/managing-projects/).

This article in particular is helpful to [apply labels to issues](https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/) so you can organize and track bugs, features, etc. :)

**Comment by tea3** [comment]
@matthewsanders Thank you for teaching me. I'll organize and track bugs, features :)
