### ISSUE TITLE
Support for <amp-video>

### ISSUE THREAD

**Issue by JMPerez** [tea3/hexo-generator-amp#12]
It would be great if the library supported [`<amp-video>`](https://github.com/ampproject/amphtml/blob/master/builtins/amp-video.md)s not only the ones hosted on Youtube or Vimeo.

Since the change seems pretty straightforward I'll try to make it myself.

**Comment by JMPerez** [comment]
Something like this should work:

```js
    var jsdom = require("jsdom").jsdom;
    var document = jsdom(replaceStr);
    var window = document.defaultView;
    var document = window.document;

    [].slice.call(document.querySelectorAll('video')).forEach(function(video) {
      var ampVideo = document.createElement('amp-video');
      // copy attributes
      [].slice.call(video.attributes).forEach(function(attribute) {
        ampVideo.setAttribute(attribute.name, attribute.value);
      });
      // move children
      [].slice.call(video.querySelectorAll('source')).forEach(function(child) {
        ampVideo.appendChild(child);
      });
      video.parentNode.replaceChild(ampVideo, video);
    });

    replaceStr = document.body.innerHTML;
```

This introduces a dependency on `jsdom` but I think it is really handy and less error-prone than dealing with regexes.

**Comment by tea3** [comment]
@JMPerez 

Thank you for your advice. I'll take care of `jsdom` if i have time. I appreciate your continued support and encouragement :D

**Comment by JMPerez** [comment]
@tea3 Thanks for adding support for `<video />`!
