### ISSUE TITLE
My page set force https by javascript, then amp what can i do this?

### ISSUE THREAD

**Issue by ky0ncheng** [tea3/hexo-generator-amp#18]
Because use static pages, not set httpserver (such as nginx/apache etc.) .

```
var url = window.location.href;
if (url.indexOf("https") < 0) {
    url = url.replace("http:", "https:");
    window.location.replace(url);
}
```

**Comment by tea3** [comment]
@ky0ncheng
I think that you do not need to do anything about `hexo-generator-amp` .  Can not open AMP HTML page with HTTPS ?

**Comment by ky0ncheng** [comment]
@tea3 thx,I can edit sample-amp.ejs
