### ISSUE TITLE
When it converting the image, it convert the noemal pages image

### ISSUE THREAD

**Issue by AkarinServer** [tea3/hexo-generator-amp#22]
For example, <amp-img src="images/source/1.png" width="459" height="192" layout="responsive"></amp-img>

It will convert this code in normal pages so that normal pages' image won't work.

And it seems it can't be seperate for CDN images. Such as in the normal pages it use website image's address "google.com/1.jpg" and in the AMP it uses local image's address "/images/1.jpg"

**Comment by tea3** [comment]
This plugin uses the same image path.  For what reason do you want to seperate image's address it?

**Comment by AkarinServer** [comment]
It seems it will ignore the website image's address.

**Comment by tea3** [comment]
For example, if you change `google.com / 1.jpg` to `https://google.com/1.jpg`, will it work well?

**Comment by AkarinServer** [comment]
no...it will ignore it. I think your plugins has some conflict with other plugins that i am using.

**Comment by tea3** [comment]
@AkarinServer 

I see. I would like to look for the cause. Please tell me your the following emvironment.

- Node version(`node -v`)
- Your site `_config.yml`
- Your theme `_config.yml`
- Plugin version(`npm ls --depth 0`)

This plugin currently does not seem to work well with hexo@3.2 . If it is possible, would you please verify that it works with hexo 3.1 ?

**Comment by tea3** [comment]
@AkarinServer This plugin fixed bugs about hexo3.2 . Do similar problems occur in the new version ?

**Comment by AkarinServer** [comment]
i'm not sure... let me try it

2017年3月30日 21:41，"tea" <notifications@github.com>写道：

**Comment by AkarinServer** [comment]
![image](https://cloud.githubusercontent.com/assets/12603846/24502663/87cb6d60-159a-11e7-9fd3-54f1ed447719.png)

this won't work on AMP pages, but my normal page is correct

**Comment by AkarinServer** [comment]
but it's works find with the local image.

**Comment by tea3** [comment]
Do it work well when change as follows ?

```
<img src="/images/source/vmware2.png" alt="pic">

or 

<img src="https://www.akarin.top/images/source/vmware2.png" width="800" height="600" alt="pic">
```

**Comment by AkarinServer** [comment]
well actually I have to say that I can't change the page source, I change it in the markdown file...

with markdown, i use '1[pic](/source/xxx.jpg)', and it will work ,but when I link to a website source, it won't work and the page's source code will look like the picture I posted

**Comment by tea3** [comment]
@AkarinServer 

`<amp-img>` tag  shoud be clearly indicate the height and width . But , this plugin can't get the width and height of image contain the external URL .

https://github.com/ampproject/amphtml/blob/master/builtins/amp-img.md
> amp-img components, like all externally fetched AMP resources, must be given an explicit size (as in width / height) in advance

Sorry , For this reason, this plugin replace the  code like the image you posted.

**Comment by AkarinServer** [comment]
so is that means amp pages only can work with local image?

2017年3月31日 01:09，"tea" <notifications@github.com>写道：

@AkarinServer <https://github.com/AkarinServer>

<amp-img> tag shoud be clearly indicate the height and width . But , this
plugin can't get the width and height of image contain the external URL .

https://github.com/ampproject/amphtml/blob/master/builtins/amp-img.md

amp-img components, like all externally fetched AMP resources, must be
given an explicit size (as in width / height) in advance

Sorry , For this reason, this plugin replace the code like the image you
posted.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tea3/hexo-generator-amp/issues/22#issuecomment-290422239>,
or mute the thread

**Comment by tea3** [comment]
@AkarinServer 
I recommend local image.  Alternatively,  if you use external image , please describe the `width` and `height`( or `data-height`) explicitly. 

```
<img src="/images/source/vmware2.png" alt="pic">

or 

<img src="https://www.akarin.top/images/source/vmware2.png" width="800" height="600" alt="pic">
```

**Comment by AkarinServer** [comment]
thanks.

2017年3月31日 01:17，"tea" <notifications@github.com>写道：

@AkarinServer <https://github.com/AkarinServer>
I recommend local image. Alternatively, if you use external image , please
describe the width and height( or data-height) explicitly.

<img src="/images/source/vmware2.png" alt="pic">

or

<img src="https://www.akarin.top/images/source/vmware2.png"
width="800" height="600" alt="pic">

—

You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tea3/hexo-generator-amp/issues/22#issuecomment-290424331>,
or mute the thread

**Comment by tea3** [comment]
@AkarinServer 
I'm Sorry , I do not know how to get the width and height of the external image at the present time.  If a good solution  found , I will be updated plugin.

**Comment by tea3** [comment]
@AkarinServer 
I supported external iamge.  [hexo-generator-amp@2.0.13](https://github.com/tea3/hexo-generator-amp/releases) automatically acquires the width and height of the external image. Please try new version.

**Comment by AkarinServer** [comment]
It seems it worked, thanks very much for your working.
