### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by ky0ncheng** [tea3/hexo-generator-amp#23]
INFO  Start processing
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND suishoshizuku.com suishoshizuku.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

------
Latest version need verify file URL ?

INFO  Start processing
[17:52:25.217] [hexo-generator-amp] error:  TypeError: unsupported file type: undefined (file: undefined)
 This plugin gets width and height by accessing the external image. However, the plugin could not access the external image. Please confirm that the image URL is correct. Or, add the width and height to the post. : http://wx3.sinaimg.cn/wp-content/uploads/2014/08/ublock1.png
Please check the following file.
-> _posts/ublock.md

This URL is invalid.

**Comment by tea3** [comment]
@ky0ncheng The latest version checks whether the image URL exists. Please tell me if there is inconvenience about this function.
