### ISSUE TITLE
Support different path for amp files.

### ISSUE THREAD

**Issue by TooBug** [tea3/hexo-generator-amp#24]
There is no way to specify the generated amp files' path, and this may lead to problem sometimes.

```
FATAL ENOTDIR: not a directory, mkdir '/Users/TooBug/xxx/public/article/post-title.html/amp'
```

My blog for example:

Hexo generate the blog post html file in a individual  folder in general, maybe `post-title/index.html`, thus the url might be `http://localhost:4000/post/post-title/`. But it's possible to modify the default path of generated blog posts by `permalink` config. For backwards compatible, I changed this config to 

```
permalink: article/:title.html
```

Then the generated path would be something like `post-title.html`, there is no folder here. But the amp plugin still tries to write amp files to `post-title.html/amp/index.html`, this lead to the error.

Hope there would be a config to specify the path of generated amp files.

**Comment by tea3** [comment]
@TooBug 

Added `generateAmpPath` Option. Please update this plugin.

```
generator_amp:
  generateAmpPath: article/amp/:title.html  #(optional) Custom AMP HTML Path
```

**Comment by TooBug** [comment]
Awesome! Thanks for all your effects. I'll try it again.
