### ISSUE TITLE
Publish on AMPThemes.io

### ISSUE THREAD

**Issue by cborodescu** [tea3/hexo-generator-amp#30]
Hi there,

This is Ciprian from AMPThemes.io - a market place for AMP themes. I noticed your hexo-generator-amp here on GitHub and I wanted to ask if it would be OK with you to publish it on AMPThemes.io as a freebie, mentioning you as an author and all. Looking forward to hearing your thoughts.

**Comment by tea3** [comment]
@cborodescu 
Thank you . I don't know what kind of websites , but that wouldn't be a problem to introduce this plugin.
