### ISSUE TITLE
Cannot use yarn to install in windows 10

### ISSUE THREAD

**Issue by maple3142** [tea3/hexo-generator-amp#33]
As title.
I use `yarn add hexo-generator-amp` will show the error below.
```
error C:\Users\Administrator\Documents\blog\node_modules\amphtml-validator: Command failed.
Exit code: 1
Command: \bin\sh -c "exit 0" 2> postinstall.DELETEME && rm postinstall.DELETEME || node postinstall-windows.js
Arguments:
Directory: C:\Users\Administrator\Documents\blog\node_modules\amphtml-validator
Output:
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:489:7)
    at Object.<anonymous> (C:\Users\Administrator\Documents\blog\node_modules\amphtml-validator\postinstall-windows.js:43:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

But use `npm i -S hexo-generator-amp` works

node 8.1.4
npm 5.0.3
yarn 1.2.1

**Comment by tea3** [comment]
It may be the same as the following issue. 

https://github.com/ampproject/amphtml/issues/10854
https://github.com/ampproject/amphtml/pull/8115

 Does the same problem occur even if installing only `amphtml-validator` ?

```
yarn add amphtml-validator
```

**Comment by tea3** [comment]
@maple3142
Have you this issue solved ? I got some advice on the following issue, will you be helpful?
https://github.com/ampproject/amphtml/issues/11977

**Comment by maple3142** [comment]
Sorry, I just forgot about this issue...
And after a few test I find I only can't install `amphtml-validator` with yarn under win10.
When I use `bash on windows` it can install correctly, maybe this is a yarn bug on win10

**Comment by tea3** [comment]
https://github.com/yarnpkg/yarn/issues/4918
