### ISSUE TITLE
is it possible to customize output path?

### ISSUE THREAD

**Issue by budaig** [tea3/hexo-generator-amp#39]
hi, @tea3 
Thanks for your plugin. successfully generated amp for my site.
i tried two configurations setting permalink in site _config.yml not theme _config.yml, with different output:

1. permalink: :category/:abbrlink.html/   Output file path is www.xxx.site/category/:abbrlink.html/amp/
2. permalink: :category/:abbrlink.html   Output file path is www.xxx.site/category/:abbrlink.htmlamp/

a / must set after the permalink, otherwise, www.xxx.site/category/:abbrlink.html/amp/ will show 404 not found.

another question, This plugin generated the AMP HTML. Output file path is ./your-posts-parmalink/amp/, is it possible to customize the output path? such as www.xxx.site/amp/category/:abbrlink.html ?

thanks.

**Comment by tea3** [comment]
@budaig 
Can you solve the problem by reading the following link?
https://github.com/tea3/hexo-generator-amp/pull/36#issuecomment-370333275
