### ISSUE TITLE
Add support for mathjax

### ISSUE THREAD

**Issue by VicaYang** [tea3/hexo-generator-amp#42]
Hi, I am using your hexo-generator-amp plugin and that works quite well. However, I notice that because the amp disallow the third party javascript, the formula I write in `.md` could not be render correctly in amp page.

I notice that amp has support [MathML](https://www.ampproject.org/docs/reference/components/amp-mathml) in the beginning of 2018. So I would like to do a little change: when generate the amp page, use the regex to replace `$(.*)$` and `$$(.*)$$` to `<amp-mathml layout="container" data-formula="\[ (.*) \]">
</amp-mathml>`

Do you know any idea how to render the formula elegantly except this method?  Also, could you provide some hints or information about how and where should I modify the code? I guess I should add a `formula.js` in the filter to do the replacement and call it in `generator.js`. Am I correct? I am willing to make a contribution!

**Comment by tea3** [comment]
@VicaYang 
Thank you for using this plugin. As you think, I'd be happy to create `formula.js` and add it to `generator.js`.

About `fomula.js` , Is the following code helpful ?
https://github.com/tea3/hexo-generator-amp/blob/master/lib/filter/vimeo.js#L21
https://github.com/tea3/hexo-generator-amp/blob/master/lib/filter/vimeo.js#L25

About how to add fomula.js to generator.js , Is the following code helpful ?
https://github.com/tea3/hexo-generator-amp/blob/master/lib/generator.js#L29
https://github.com/tea3/hexo-generator-amp/blob/master/lib/generator.js#L111

**Comment by VicaYang** [comment]
@tea3 Thankyou! I have complete the naive version and test on my blog (e.g. [Analysis-of-Covariance](https://blog.vicayang.cc/Note-Analysis-of-Covariance/amp/)). But I am afraid of that will fail because of some other "dirty" case. What should I do next?
