### ISSUE TITLE
rel="amphtml" Content After Changed Link Structure

### ISSUE THREAD

**Issue by hifocus** [tea3/hexo-generator-amp#47]
# Question:

My Hexo Blog's permanent link structure is like this: `:title.html`, for example, if my title is `hello-world`, the permanent link will be `blogsite.com/hello-world.html`.

While configuring this plugin, I found that under my link settings, the plugin could not generate contents like `/public/hello-world.html/amp/index.html`. So `generateAmpPath: :title.html/amp/  #(optional) Custom AMP HTML Path` will not work.

I looked into https://github.com/tea3/hexo-generator-amp/issues/24 and followed your instruction to change the `generateAmpPath` variable into `generateAmpPath: amp/:title.html`, then it does work and able to generate the amp static files for me.

But according to the instruction in README as well as https://github.com/tea3/hexo-generator-amp/issues/14, I put the following code into `path\to\hexo\themes\next\layout\_partials\head\head.swig`
```swig
{% if is_post() && config.generator_amp %}
  <link rel="amphtml" href="./amp/index.html">
{% endif %}
```
But currently the amp generate location has been changed, `./amp/index.html` will be a 404 for sure, so what should I do to make the `amphtml` tag to work?

Many thanks for all the effects in developing this plugin whilst answering questions like this one. More details are provided below.

<hr>

OS version

- Windows (please tell me version)
Windows 10 1809

Node version(`node -v`)
```
v10.7.0
```

Plugin version(`npm ls --depth 0`) 
I dont know why these errors occur.
```
npm ERR! missing: mkdirp@0.5.1, required by node-pre-gyp@0.10.3
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: minimatch@3.0.4, required by ignore-walk@3.0.1
npm ERR! missing: brace-expansion@1.1.11, required by minimatch@3.0.4
npm ERR! missing: balanced-match@1.0.0, required by brace-expansion@1.1.11
npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.11
npm ERR! missing: console-control-strings@1.1.0, required by npmlog@4.1.2
npm ERR! missing: inherits@2.0.3, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.2, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.2, required by string_decoder@1.1.1
npm ERR! missing: console-control-strings@1.1.0, required by gauge@2.7.4
npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0.2
npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.0.0
npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.3
npm ERR! missing: inherits@2.0.3, required by glob@7.1.3
npm ERR! missing: minimatch@3.0.4, required by glob@7.1.3
npm ERR! missing: once@1.4.0, required by glob@7.1.3
npm ERR! missing: once@1.4.0, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: minipass@2.3.5, required by tar@4.4.8
npm ERR! missing: mkdirp@0.5.1, required by tar@4.4.8
npm ERR! missing: safe-buffer@5.1.2, required by tar@4.4.8
npm ERR! missing: yallist@3.0.3, required by tar@4.4.8
npm ERR! missing: minipass@2.3.5, required by fs-minipass@1.2.5
npm ERR! missing: safe-buffer@5.1.2, required by minipass@2.3.5
npm ERR! missing: yallist@3.0.3, required by minipass@2.3.5
npm ERR! missing: minipass@2.3.5, required by minizlib@1.2.1
npm ERR! peer dep missing: eslint@>= 4.12.1, required by babel-eslint@10.0.1
```

Again, thanks a lot.

**Comment by hifocus** [comment]
I've deployed my current configures into https://justhx.com, a live link to the amp page: https://justhx.com/amp/hello-world.html

**Comment by tea3** [comment]
@hifocus 
Thank you for using this plugin. It does not work in `generateAmpPath: :title.html/amp/` as you say. `generateAmpPath: amp/:title.html` would be better.

How about changing the AMP path of the template as follows ?

```
{% if is_post() && config.generator_amp %}
  <link rel="amphtml" href="{{ config.url }}{{ config.root }}amp/{{ page.path }}">
{% endif %}
```

**Comment by hifocus** [comment]
Sorry for the late reply, I've been working on other stuff.

I will notify you once I have tested your code. It looks fine, thanks for that.

Hope you have an awesome day there!
