### ISSUE TITLE
Consider adding layout="responsive" to example template for images.

### ISSUE THREAD

**Issue by matthewsanders** [tea3/hexo-generator-amp#5]
Could simply default to responsive:

`<amp-img src="/<%= config.generator_amp.logo.path %>" width="<%= config.generator_amp.logo.width %>" height="<%= config.generator_amp.logo.height %>" layout="responsive">`

OR

could add this as a configuration. #9

**Comment by tea3** [comment]
@matthewsanders Thank you very much.
