### ISSUE TITLE
Fix relative path inconsistencies

### ISSUE THREAD

**Issue by matthewsanders** [tea3/hexo-generator-amp#6]
currently the configuration seems to use three different relative paths:

1. logo - path is relative to public site layout
2. avatar - path is relative to post (this seems incorrect as you could easily share this resource in a root directory aka about/profile.jpg)
3. css and ejs templates - path is relative to the hexo install location

Item 2. above is probably the most troublesome.

**Comment by tea3** [comment]
@matthewsanders 
Thank you for pointing it out.  I'll consider it.

**Comment by matthewsanders** [comment]
I'm not sure I follow what the templateDir and assetDistDir parameters are supposed to be and if a copyAssets stage is actually needed.

Could you explain this more?

The main issue I noticed originally is that there were three different paths to keep track of in the config file and that the avatar path was assumed to live inside each post rather then potentially shared.

The default behavior of hexo is to copy files from source to public unless the folder starts with "_" so if I had a "source/amp" folder it would become "public/amp" which could contain any shared assets.  I would expect to reference them in the config as if they are in public ex: "amp/asset_name.png".  So I could reference my shared logo, avatar, and title image relative to public. (Note: it would be ideal as noted in my other issue  #11 to treat the search engine banner and the site banner separately.  Obviously people could configure this themselves since they are overriding the .css and .ejs anyway, so long as it isn't required in the js of the plugin)

For templates (ejs, css) I was initially using a "source/_amp_template" folder to hold my *.css and *.ejs files so in that case it made sense to be relative to "source" folder as the generator consumed them as templates rather then final assets. (these could also possibly be overridden by Front-matter at some point to allow per post layouts).  The css and ejs are then used to generate the html by this plugin already in the public folder under each post's "amp" folder.  Each post would then put any potentially amp specific assets in the "amp" folder as well (these are likely coming in as overrides in Front-matter, or tags).

So in this case the shared images in the config would be specified relative to public, the template (ejs, css) would be specified relative to source, and per post config would only come from future front-matter or possibly tags that could be added to this plugin.

I guess the main issue I had before was primarily the avatar configuration.  If I'm missing something with the copyAssets stage please let me know.

**Comment by tea3** [comment]
@matthewsanders 
I'm Sorry. Three different relative paths is hard to understand.  I wanted to eliminate of them. So, this fix in order to launch more easy. 

Front-matter update #11 Consider now .
