### ISSUE TITLE
Consider using a child directory to contain amp page and assets.

### ISSUE THREAD

**Issue by matthewsanders** [tea3/hexo-generator-amp#7]
It would probably be a better choice to create an `amp` sub folder to contain the index.html and any amp specific assets that may need generated.

**Comment by matthewsanders** [comment]
This seems to be the approach taken by the WordPress plugin as well.  https://wordpress.org/plugins/amp/

**Comment by matthewsanders** [comment]
Note this does require a change to the sample template.

`<link rel="canonical" href="../index.html" >` Note two `..`

**Comment by tea3** [comment]
@matthewsanders  Thank you for fixing template. That's a big help : )
