### ISSUE TITLE
Consider adding Front-matter option for substituteTitleImage

### ISSUE THREAD

**Issue by matthewsanders** [tea3/hexo-generator-amp#8]
It would be a good idea to allow the user to override the substituteTitleImage on a per post basis.

**Comment by tea3** [comment]
@matthewsanders  Thank you. It is a good idea.  For example, Is your idea is like this?

your-post.md
``` markdown
---
title: Hello World
substituteTitleImage: postImage.jpg
---
## Hello world
...
```

**Comment by matthewsanders** [comment]
Yup.  Pretty much.

We may actually want to change the semantics a bit though.  Basically IFF it is overridden in the front-matter it will take effect first.
